# Generated by Django 5.1.4 on 2025-07-23 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('is_national', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.region')),
            ],
        ),
        migrations.CreateModel(
            name='HealthStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('structure_type', models.CharField(choices=[('hospital', 'Hôpital'), ('clinic', 'Clinique'), ('health_center', 'Centre de santé'), ('pharmacy', 'Pharmacie'), ('emergency', "Service d'urgence")], max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.region')),
            ],
        ),
    ]
