# Generated by Django 5.1.4 on 2025-07-23 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('situation', models.CharField(choices=[('personne_agee', 'Personne âgée'), ('femme_enceinte', 'Femme enceinte'), ('personne_risque', 'Personne à risque'), ('enfant', 'Enfant'), ('aucune', 'Aucune situation particulière')], max_length=20)),
                ('temperature_threshold', models.FloatField()),
                ('message_template', models.TextField()),
                ('recommendations', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultilingualAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('tres_dangereux', 'Très dangereux'), ('dangereux', 'Dangereux'), ('tres_inconfortable', 'Très inconfortable'), ('inconfortable', 'Inconfortable')], max_length=20)),
                ('description_fr', models.TextField(verbose_name='Description (Français)')),
                ('description_wolof', models.TextField(blank=True, verbose_name='Description (Wolof)')),
                ('description_poular', models.TextField(blank=True, verbose_name='Description (Poular)')),
                ('audio_message', models.FileField(blank=True, null=True, upload_to='alerts/audio/')),
                ('admin_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expirée')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalizedAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('heat_wave', 'Vague de chaleur'), ('health_risk', 'Risque sanitaire'), ('weather_warning', 'Alerte météo'), ('emergency', 'Urgence')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('message_wolof', models.TextField(blank=True)),
                ('message_poular', models.TextField(blank=True)),
                ('audio_message', models.FileField(blank=True, null=True, upload_to='alerts/audio/')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
