# Generated by Django 5.1.4 on 2025-07-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertTemplate',
        ),
    ]
