# Generated by Django 5.1.4 on 2025-07-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_delete_alerttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('situation', models.CharField(choices=[('personne_agee', 'Personne âgée'), ('femme_enceinte', 'Femme enceinte'), ('personne_risque', 'Personne à risque'), ('enfant', 'Enfant'), ('aucune', 'Aucune situation particulière')], max_length=20)),
                ('temperature_threshold', models.FloatField()),
                ('message_template', models.TextField()),
                ('recommendations', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
